# Generated by Django 2.2.1 on 2020-03-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('area', models.TextField(max_length=40)),
                ('service', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tags', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
            ],
        ),
    ]
